<?php

namespace App\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * CartProductRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CartProductRepository extends EntityRepository
{
}
