<?php

namespace App\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
}
